version: '3.9'
services:
  prisma-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    depends_on:
      - postgres
  postgres:
    # using postgress version 14.3 in specific because of the AWS Aurora
    image: postgres:14.3-alpine
    command: ['postgres', '-c', 'log_statement=all']
    container_name: prisma-api-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma-api-dev
    ports:
      - '5557:5432'
    volumes:
      - prisma-api-postgres:/var/lib/postgresql/data
volumes:
  prisma-api-postgres:
    name: prisma-api-postgres
